export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

// details page calls
export const COURSE_DETAILS = 'COURSE_DETAILS';

export const BUY_COURSE = 'BUY_COURSE';
export const TOGGLE_COURSE_COMPLETION = 'TOGGLE_COURSE_COMPLETION';